'use client';
import { useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { useNavigate,useParams } from '../router.js';
import { PageHeader,Button,Card,SectionCard,Badge,Icon,Switch,Modal } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { createAnnouncement,publishAnnouncement,updateAnnouncement } from '../mock/api.js';
import './Engagement.css';
const TYPES=[['System','radio-tower','System related updates'],['Feature','star','New features / updates'],['Update','info','Important updates'],['Notice','bell','General notices'],['Reminder','clock-3','Reminders'],['Campaign','megaphone','Promotions / campaigns']];
const AUDIENCES=[['All Users','Send to all users in the system'],['Users with Access','Send to users with specific module access'],['User Roles','Send to specific user roles'],['Custom Users','Select specific users']];
const EMPTY={title:'',message:'',type:'System',audience:'All Users',schedule:'Publish Now',scheduleDate:'',scheduleTime:'',priority:'Normal',pinned:false,expiry:'',acknowledgement:true};
export function AnnouncementForm({editing=false}){
 const navigate=useNavigate(),params=useParams(),search=useSearchParams(),rows=useCollection('announcements')||[],existing=rows.find(r=>r.id===params.announcementId),copy=rows.find(r=>r.id===search.get('copy'));
 const [form,setForm]=useState(EMPTY),[review,setReview]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const source=editing?existing:copy;if(source)setForm({...EMPTY,title:copy?source.t+' (Copy)':source.t,message:source.p,type:source.type,audience:source.aud,priority:source.priority||'Normal',pinned:!!source.pinned,acknowledgement:source.acknowledgement!==false})},[editing,existing,copy]);
 function set(key,value){setForm(f=>({...f,[key]:value}))}function validate(){if(!form.title.trim()||!form.message.trim()){setError('Title and message are required.');return false}setError('');return true}
 async function save(status){if(!validate())return;setSaving(true);const typeMeta=TYPES.find(t=>t[0]===form.type);const changes={t:form.title,p:form.message,type:form.type,icon:typeMeta[1],tone:form.type==='Feature'?'green':form.type==='Notice'||form.type==='Campaign'?'purple':'blue',aud:form.audience,st:status,d:status==='Scheduled'?(form.scheduleDate||'Scheduled'):status==='Published'?'Just now':'—',tm:status==='Scheduled'?form.scheduleTime:'',v:status==='Published'?0:null,priority:form.priority,pinned:form.pinned,expiry:form.expiry,acknowledgement:form.acknowledgement};let row;if(editing)row=await updateAnnouncement(existing.id,changes);else row=await createAnnouncement(changes);setSaving(false);setReview(false);navigate('/announcements/'+row.id)}
 if(editing&&!existing)return <Card>Announcement not found.</Card>;
 return <div className="engagement-page"><Button variant="outline" icon="arrow-left" style={{justifySelf:'start'}} onClick={()=>navigate('/announcements')}>Back to Announcements</Button><PageHeader crumbs={['Support System','Announcements',editing?'Edit Announcement':'New Announcement']} title={editing?'Edit Announcement':'New Announcement'} description="Create and send an announcement to keep your users informed."/>
 <div className="announcement-form-layout"><div className="announcement-form-main"><Card className="announcement-card"><label><span className="eng-label">Title <em>*</em></span><div style={{position:'relative'}}><input className="eng-input" maxLength={100} placeholder="Enter announcement title" value={form.title} onChange={e=>set('title',e.target.value)}/><small className="tk-meta" style={{position:'absolute',right:9,top:11}}>{form.title.length}/100</small></div><small className="tk-meta">Keep it short, clear and descriptive.</small></label>
 <label><span className="eng-label">Message <em>*</em></span><div className="eng-editor"><div className="eng-editor-tools"><button type="button">Paragraph⌄</button>{['B','I','U','S','☷','≡','↔','🔗','▧','▦','—','↶','↷'].map((x,i)=><button type="button" key={i} onClick={()=>set('message',form.message+x)}>{x}</button>)}</div><textarea maxLength={5000} placeholder="Write your announcement message..." value={form.message} onChange={e=>set('message',e.target.value)}/><div className="tk-meta" style={{textAlign:'right',padding:'0 9px 7px'}}>{form.message.length}/5000</div></div></label>
 <div><span className="eng-label">Announcement Type <em>*</em></span><div className="choice-grid">{TYPES.map(([name,icon,hint])=><button type="button" className={'choice-card '+(form.type===name?'active':'')} key={name} onClick={()=>set('type',name)}><strong><Icon name={icon} size={13} color="var(--tk-blue)"/>{name}</strong><small>{hint}</small></button>)}</div></div>
 <div><span className="eng-label">Audience <em>*</em></span><div className="audience-grid">{AUDIENCES.map(([name,hint])=><button type="button" className={'audience-choice '+(form.audience===name?'active':'')} key={name} onClick={()=>set('audience',name)}><i className="eng-dot"/><span><strong>{name}</strong><small>{hint}</small></span></button>)}</div></div>
 <div><span className="eng-label">Schedule</span><div className="schedule-grid"><button type="button" className={'audience-choice '+(form.schedule==='Publish Now'?'active':'')} onClick={()=>set('schedule','Publish Now')}><i className="eng-dot"/><span><strong>Publish Now</strong><small>Publish immediately</small></span></button><button type="button" className={'audience-choice '+(form.schedule==='Schedule for Later'?'active':'')} onClick={()=>set('schedule','Schedule for Later')}><i className="eng-dot"/><span><strong>Schedule for Later</strong><small>Choose date and time</small></span></button></div>{form.schedule==='Schedule for Later'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:10}}><input aria-label="Schedule date" type="date" className="eng-input" value={form.scheduleDate} onChange={e=>set('scheduleDate',e.target.value)}/><input aria-label="Schedule time" type="time" className="eng-input" value={form.scheduleTime} onChange={e=>set('scheduleTime',e.target.value)}/></div>}</div>{error&&<p style={{margin:0,color:'var(--tk-danger)',fontSize:12}}>{error}</p>}</Card><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Button onClick={()=>{if(validate())setReview(true)}}>Review &amp; Publish</Button><Button variant="outline" disabled={saving} onClick={()=>save('Draft')}>Save as Draft</Button></div></div>
 <div className="announcement-form-rail"><SectionCard title="Announcement Settings"><label><span className="eng-label">Priority</span><select className="eng-input" value={form.priority} onChange={e=>set('priority',e.target.value)}>{['Low','Normal','High','Urgent'].map(x=><option key={x}>{x}</option>)}</select><small className="tk-meta">Priority controls the display order.</small></label><div className="eng-setting"><span><strong>Pin to Top</strong><small>Pinned announcements always appear at the top.</small></span><Switch checked={form.pinned} onChange={v=>set('pinned',v)}/></div><div className="eng-setting"><span><strong>Expiry Date (Optional)</strong><small>Announcement will be hidden after this date.</small></span></div><input aria-label="Expiry date" type="date" className="eng-input" value={form.expiry} onChange={e=>set('expiry',e.target.value)}/><div className="eng-setting"><span><strong>Allow Acknowledgement</strong><small>Users will be required to acknowledge this announcement.</small></span><Switch checked={form.acknowledgement} onChange={v=>set('acknowledgement',v)}/></div></SectionCard>
 <SectionCard title="Live Preview"><div className="live-preview"><div style={{display:'flex',justifyContent:'space-between'}}><Badge tone="info">{form.type.toUpperCase()}</Badge><small>Just now</small></div><strong>{form.title||'This is a sample announcement title'}</strong><p>{form.message||'This is how your announcement will appear to users. Make sure the information is clear and easy to understand.'}</p>{form.acknowledgement&&<div style={{marginTop:10,paddingTop:8,borderTop:'1px solid #c4d5ff',fontSize:9,color:'var(--tk-blue)'}}><Icon name="shield-check" size={11}/> Acknowledgement Required</div>}</div></SectionCard><SectionCard title="Tips for Effective Announcements" icon="lightbulb"><div className="tips-list">{['Use clear and concise titles','Start with the most important information','Keep the message short and actionable','Use the right type for better visibility','Pin important announcements to the top'].map(x=><span key={x}><Icon name="check" size={11} color="var(--tk-blue)"/>{x}</span>)}</div></SectionCard></div></div>
 <Modal open={review} onClose={()=>setReview(false)} title="Review Announcement" description="Confirm how this announcement will be delivered." width={560} footer={<><Button variant="outline" onClick={()=>setReview(false)}>Keep Editing</Button><Button disabled={saving} icon="send" onClick={()=>save(form.schedule==='Schedule for Later'?'Scheduled':'Published')}>{form.schedule==='Schedule for Later'?'Schedule Announcement':'Publish Now'}</Button></>}><div className="live-preview"><Badge tone="info">{form.type}</Badge><h3>{form.title}</h3><p style={{whiteSpace:'pre-line'}}>{form.message}</p><div className="tk-meta" style={{marginTop:12}}>Audience: {form.audience} · Priority: {form.priority}</div></div></Modal></div>
}
