'use client';
import { useMemo,useState } from 'react';
import { useNavigate } from '../router.js';
import { PageHeader,Button,StatCard,Card,SectionCard,Tabs,SearchField,DataTable,Pagination,Badge,Icon,DropdownMenu } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { publishAnnouncement,updateAnnouncement } from '../mock/api.js';
import './Engagement.css';
const PAGE_SIZE=8;
const TONE={System:'info',Feature:'success',Update:'info',Notice:'purple',Reminder:'warning',Campaign:'purple'};
const ICON={System:'megaphone',Feature:'sparkles',Update:'info',Notice:'calendar-days',Reminder:'clock-3',Campaign:'send'};
function csvExport(rows){const csv=[['Announcement','Type','Audience','Status','Date','Views'],...rows.map(r=>[r.t,r.type,r.aud,r.st,r.d,r.v??''])].map(x=>x.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='announcements.csv';a.click();URL.revokeObjectURL(u)}
export function Announcements(){
 const navigate=useNavigate(),rows=useCollection('announcements')||[];
 const [tab,setTab]=useState('All Announcements'),[q,setQ]=useState(''),[status,setStatus]=useState('All'),[type,setType]=useState('All'),[audience,setAudience]=useState('All'),[page,setPage]=useState(1),[menu,setMenu]=useState(null),[toast,setToast]=useState('');
 const filtered=useMemo(()=>rows.filter(r=>(tab==='All Announcements'||r.st===tab.replace(/s$/,''))&&(status==='All'||r.st===status)&&(type==='All'||r.type===type)&&(audience==='All'||r.aud===audience)&&(!q||[r.t,r.p,r.id].some(v=>v.toLowerCase().includes(q.toLowerCase())))),[rows,tab,status,type,audience,q]);
 const paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);function notify(s){setToast(s);setTimeout(()=>setToast(''),1600)}
 return <div className="engagement-page"><PageHeader crumbs={['Support System','Announcements']} title="Announcements" description="Create, manage and broadcast important updates to users." actions={<><Button variant="outline" icon="download" onClick={()=>csvExport(filtered)}>Export</Button><Button icon="plus" onClick={()=>navigate('/announcements/new')}>New Announcement</Button></>}/><div className="engagement-stats"><StatCard icon="megaphone" label="Total Announcements" value="24" delta="14%" caption="from last 30 days"/><StatCard icon="send" tint="green" label="Published" value="18" delta="12%" caption="from last 30 days"/><StatCard icon="calendar" label="Scheduled" value="5" delta="5%" caption="from last 30 days"/><StatCard icon="eye" tint="purple" label="Total Views" value="8,432" delta="18%" caption="from last 30 days"/></div>
 <div className="engagement-layout"><SectionCard title="" pad="none"><Tabs value={tab} onChange={v=>{setTab(v);setPage(1)}} items={['All Announcements','Published','Scheduled','Drafts','Expired']} style={{padding:'0 16px'}}/><div className="engagement-toolbar"><SearchField className="search" style={{flex:1}} placeholder="Search announcements..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select aria-label="Status filter" className="engagement-select" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{['All','Published','Scheduled','Draft','Expired'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Type filter" className="engagement-select" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option>All</option>{Object.keys(ICON).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Audience filter" className="engagement-select" value={audience} onChange={e=>{setAudience(e.target.value);setPage(1)}}><option>All</option>{[...new Set(rows.map(r=>r.aud))].map(x=><option key={x}>{x}</option>)}</select><Button variant="outline" icon="rotate-ccw" onClick={()=>{setQ('');setStatus('All');setType('All');setAudience('All');setPage(1)}}>Reset</Button></div>
 <DataTable rows={paged} rowKey={r=>r.id} onRowClick={r=>navigate('/announcements/'+r.id)} columns={[{key:'t',header:'Announcement',render:r=><span className="engagement-title-cell"><span className="type-icon"><Icon name={ICON[r.type]} size={15}/></span><span><strong>{r.t}</strong><small>{r.p}</small></span></span>},{key:'type',header:'Type',render:r=><Badge tone={TONE[r.type]}>{r.type}</Badge>},{key:'aud',header:'Audience'},{key:'st',header:'Status',render:r=><Badge>{r.st}</Badge>},{key:'d',header:'Published / Scheduled',render:r=><span style={{display:'grid',whiteSpace:'nowrap'}}>{r.d}<small className="tk-meta">{r.tm}</small></span>},{key:'v',header:'Views',render:r=>r.v?.toLocaleString()??'—'},{key:'x',header:'Actions',width:44,render:r=><span className="action-menu-wrap"><Button variant="ghost" icon="ellipsis" size="sm" aria-label={'Actions for '+r.t} onClick={e=>{e.stopPropagation();setMenu(menu===r.id?null:r.id)}}/>{menu===r.id&&<span style={{position:'absolute',right:0,top:34,zIndex:30}} onClick={e=>e.stopPropagation()}><DropdownMenu width={210} items={[{label:'View Announcement',icon:'eye',onClick:()=>navigate('/announcements/'+r.id)},{label:'Edit Announcement',icon:'pencil',onClick:()=>navigate('/announcements/'+r.id+'/edit')},r.st!=='Published'?{label:'Publish Now',icon:'send',onClick:()=>{publishAnnouncement(r.id);setMenu(null);notify('Announcement published')}}:{label:'Unpublish',icon:'archive',onClick:()=>{updateAnnouncement(r.id,{st:'Draft',d:'—',tm:''});setMenu(null);notify('Moved to drafts')}},{divider:true},{label:'Duplicate',icon:'copy',onClick:()=>navigate('/announcements/new?copy='+r.id)}]}/></span>}</span>}]}/>{!paged.length&&<div style={{padding:40,textAlign:'center',color:'var(--tk-ink-400)'}}>No announcements match your filters.</div>}<Pagination page={page} pageCount={Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))} pageSize={PAGE_SIZE} total={filtered.length} onPage={p=>setPage(Math.min(Math.max(1,p),Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))))}/></SectionCard>
 <div className="engagement-rail"><SectionCard title="Announcement Types">{Object.keys(ICON).map(name=><button className="engagement-side-row" key={name} onClick={()=>{setType(name);setPage(1)}}><span className="side-icon"><Icon name={ICON[name]} size={13}/></span><span><strong>{name}</strong></span><b>{rows.filter(r=>r.type===name).length}</b></button>)}<Button variant="ghost" fullWidth iconRight="arrow-right" onClick={()=>setType('All')}>View all types</Button></SectionCard><SectionCard title="Recent Announcements" action={<button className="engagement-primary" style={{border:0,background:'none'}} onClick={()=>{setTab('All Announcements');setPage(1)}}>View all</button>}>{rows.slice(0,4).map(r=><button className="engagement-side-row" key={r.id} onClick={()=>navigate('/announcements/'+r.id)}><span className="side-icon"><Icon name={ICON[r.type]} size={13}/></span><span><strong>{r.t}</strong><small>{r.d}</small></span><Badge>{r.st}</Badge></button>)}</SectionCard><Card tone="cool"><div style={{display:'flex',gap:12}}><Icon name="lightbulb" size={22} color="var(--tk-blue)"/><div><h3 style={{margin:'0 0 8px',fontSize:13}}>Tips</h3><p style={{margin:0,fontSize:11,lineHeight:1.6,color:'var(--tk-ink-500)'}}>Announcements help you keep your users informed and reduce support requests.</p></div></div><Button variant="outline" fullWidth iconRight="arrow-right" style={{marginTop:14}} onClick={()=>navigate('/knowledge-base')}>Learn more about announcements</Button></Card></div></div>{toast&&<div className="eng-toast">{toast}</div>}</div>
}
