'use client';
import { useState } from 'react';
import { useNavigate,useParams } from '../router.js';
import { PageHeader,Button,Card,SectionCard,Badge,Avatar,Icon,Modal,Textarea,Select } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { replyToFeedback,updateFeedback } from '../mock/api.js';
import './Engagement.css';
const TYPE_TONE={Praise:'success',Suggestion:'info',Issue:'danger',Other:'neutral'},TYPE_ICON={Praise:'message-square',Suggestion:'lightbulb',Issue:'triangle-alert',Other:'circle-help'};
export function FeedbackDetail(){const navigate=useNavigate(),{feedbackId}=useParams(),rows=useCollection('feedback')||[],f=rows.find(x=>x.id===feedbackId),[replyOpen,setReplyOpen]=useState(false),[reply,setReply]=useState(''),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState(''),[tag,setTag]=useState(''),[toast,setToast]=useState('');function notify(s){setToast(s);setTimeout(()=>setToast(''),1600)}if(!f)return <Card>Feedback not found.</Card>;
 async function sendReply(){if(!reply.trim())return;await replyToFeedback(f.id,reply.trim());setReplyOpen(false);setReply('');notify('Reply sent and feedback resolved')}async function saveNote(){await updateFeedback(f.id,{note:note.trim()});setNoteOpen(false);notify('Internal note saved')}async function addTag(){if(!tag.trim())return;await updateFeedback(f.id,{tags:[...new Set([...(f.tags||[]),tag.trim()])]});setTag('')}
 const related=rows.filter(x=>x.id!==f.id&&x.type===f.type).slice(0,3);
 return <div className="engagement-page"><PageHeader crumbs={['Support System','Feedback',f.title]} title="Feedback Details" description="Review the submission, user context, status and response history." actions={<><Button variant="outline" icon="arrow-left" onClick={()=>navigate('/feedback')}>Back to Feedback</Button><Button variant="outline" icon={f.unread?'mail-open':'mail'} onClick={()=>{updateFeedback(f.id,{unread:!f.unread});notify(f.unread?'Marked as read':'Marked as unread')}}>{f.unread?'Mark as Read':'Mark as Unread'}</Button><Button variant="danger" icon="ban" onClick={()=>{updateFeedback(f.id,{status:'Spam',spam:true});notify('Moved to spam')}}>Move to Spam</Button><Button icon="mail" onClick={()=>setReplyOpen(true)}>Reply to User</Button></>}/><div className="feedback-detail-grid"><div className="feedback-detail-main"><Card className="feedback-hero"><div className="feedback-hero-main"><div className="feedback-hero-title"><span className="feedback-big-icon"><Icon name={TYPE_ICON[f.type]} size={28}/></span><div><Badge tone={TYPE_TONE[f.type]}>{f.type}</Badge><h2 style={{margin:'8px 0 4px',fontSize:22,color:'var(--tk-ink-900)'}}>{f.title}</h2><div className="tk-meta">Feedback ID: {f.id}　•　{f.date} at {f.time}　•　via {f.channel}</div></div></div><div className="feedback-message">{f.body}</div></div><div className="feedback-facts"><Fact label="Submitted by" icon="user" title={f.user} detail={f.email}/><Fact label="User Type" icon="badge-check" title="Registered User" detail={`Member since ${f.memberSince}`}/><Fact label="Location" icon="map-pin" title={f.location} detail="West Africa Time (WAT)"/><Fact label="Device / Browser" icon="monitor" title={f.device} detail={f.resolution}/></div></Card>
 <SectionCard title="Feedback Details"><div className="feedback-info-grid"><Info icon="message-square" label="Type" value={<Badge tone={TYPE_TONE[f.type]}>{f.type}</Badge>}/><Info icon="bell" label="Channel" value={<><Icon name={f.channel==='Web'?'globe-2':f.channel==='Email'?'mail':'smartphone'} size={13}/> {f.channel}</>}/><Info icon="thumbs-up" label="Category / Topic" value={<Badge tone="info">{f.topic}</Badge>}/><Info icon="credit-card" label="Status" value={<select className="engagement-select" value={f.status} onChange={e=>updateFeedback(f.id,{status:e.target.value})}>{['Open','In Progress','Resolved','Spam'].map(x=><option key={x}>{x}</option>)}</select>}/><Info icon="user-round" label="Assigned To" value={<span style={{display:'flex',gap:7,alignItems:'center'}}><Avatar name={f.assignee} size={22}/><select className="engagement-select" value={f.assignee} onChange={e=>updateFeedback(f.id,{assignee:e.target.value})}>{['Unassigned','Trukkas Admin','Sarah Johnson','Sarah Wilson','David Wilson'].map(x=><option key={x}>{x}</option>)}</select></span>}/><Info icon="clock-3" label="Resolved On" value={f.resolvedOn||'—'}/></div><div className="feedback-info-row" style={{gridTemplateColumns:'145px 1fr',border:0}}><span><Icon name="hash" size={13}/> Tags</span><span className="feedback-tags">{(f.tags||[]).map(t=><Badge key={t} tone="info">{t}</Badge>)}<input aria-label="New tag" className="eng-input" style={{width:120,height:28}} placeholder="Add tag" value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addTag()}}/><Button size="sm" variant="outline" icon="plus" onClick={addTag}/></span></div></SectionCard>
 <SectionCard title="Internal Notes" icon="notebook-tabs" action={<Button size="sm" variant="outline" icon="pencil" onClick={()=>{setNote(f.note||'');setNoteOpen(true)}}>Edit</Button>}><div className="note-box">{f.note||'No internal notes have been added.'}</div>{f.note&&<div className="tk-meta" style={{marginTop:14}}>Added by Trukkas Admin · Just now</div>}</SectionCard></div>
 <div className="engagement-rail"><SectionCard title="User Information"><div style={{display:'flex',gap:10,alignItems:'center',marginBottom:14}}><Avatar name={f.user} size={42}/><div><strong style={{fontSize:12}}>{f.user}</strong><Badge tone="info" style={{display:'flex',marginTop:4}}>All Users</Badge></div></div><InfoLine label="Email" value={f.email}/><InfoLine label="Phone" value={f.phone}/><InfoLine label="Member Since" value={f.memberSince}/><InfoLine label="Total Feedback" value={f.totalFeedback}/><Button variant="outline" fullWidth style={{marginTop:12}} onClick={()=>notify('User profile opened')}>View User Profile</Button></SectionCard><SectionCard title="Conversation History"><History icon="check" title={`Feedback marked as ${f.status}`} detail={`by ${f.assignee}\n${f.resolvedOn||'Just now'}`}/>{f.reply&&<div style={{margin:'4px 0 10px 33px',padding:9,borderRadius:7,background:'var(--tk-success-soft)',color:'var(--tk-ink-700)',fontSize:9,lineHeight:15}}>{f.reply}</div>}<History icon="mail" title="Auto-acknowledgement sent" detail={`to ${f.email}\n${f.date} at ${f.time}`}/><History icon="globe-2" title="Feedback received" detail={`via ${f.channel}\n${f.date} at ${f.time}`}/><Button variant="outline" fullWidth iconRight="arrow-right" onClick={()=>notify('Full history is displayed')}>View Full History</Button></SectionCard><SectionCard title="Related Feedback" action={<button style={{border:0,background:'none',color:'var(--tk-blue)',cursor:'pointer'}} onClick={()=>navigate('/feedback')}>View all</button>}>{related.length?related.map(x=><button className="engagement-side-row" key={x.id} onClick={()=>navigate('/feedback/'+x.id)}><span className="side-icon"><Icon name={TYPE_ICON[x.type]} size={12}/></span><span><strong>{x.title}</strong><small>{x.status}　•　{x.date}</small></span></button>):<span className="tk-meta">No related feedback.</span>}</SectionCard></div></div>
 <Modal open={replyOpen} onClose={()=>setReplyOpen(false)} title={`Reply to ${f.user}`} description={f.email} width={560} footer={<><Button variant="outline" onClick={()=>setReplyOpen(false)}>Cancel</Button><Button disabled={!reply.trim()} icon="send" onClick={sendReply}>Send Reply</Button></>}><Textarea label="Message" rows={6} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a helpful response..."/></Modal><Modal open={noteOpen} onClose={()=>setNoteOpen(false)} title="Internal Note" width={520} footer={<><Button variant="outline" onClick={()=>setNoteOpen(false)}>Cancel</Button><Button onClick={saveNote}>Save Note</Button></>}><Textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a private note for the support team..."/></Modal>{toast&&<div className="eng-toast">{toast}</div>}</div>}
function Fact({label,icon,title,detail}){return <div className="feedback-fact"><label>{label}</label><div style={{display:'flex',gap:8}}><Icon name={icon} size={14} color="var(--tk-blue)"/><span><strong>{title}</strong><small>{detail}</small></span></div></div>}
function Info({icon,label,value}){return <div className="feedback-info-row"><span><Icon name={icon} size={13}/>　{label}</span><span>{value}</span></div>}
function InfoLine({label,value}){return <div style={{display:'flex',justifyContent:'space-between',gap:12,padding:'8px 0',fontSize:10}}><span style={{color:'var(--tk-ink-400)'}}>{label}</span><span style={{color:'var(--tk-ink-700)',textAlign:'right'}}>{value}</span></div>}
function History({icon,title,detail}){return <div className="history-item"><span className="history-icon"><Icon name={icon} size={11}/></span><span><strong>{title}</strong><small style={{whiteSpace:'pre-line'}}>{detail}</small></span></div>}
