'use client';
import { useMemo,useRef,useState } from 'react';
import { useNavigate } from '../router.js';
import { PageHeader,Button,StatCard,SectionCard,Card,SearchField,DataTable,Pagination,Badge,DonutChart,LegendList,RankBarList,ListRow,QuickActionsCard,IconButton,DropdownMenu,Modal,TextField,Select } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { setTruckStatus,addTruck } from '../mock/api.js';
import './FleetManagement.css';

const STATUSES=['Available','On Trip','In Maintenance','Inactive'];
const TYPES=['40FT Trailer','20FT Container','Flatbed','40FT High Cube','45FT Container','Tanker'];
const EMPTY={plate:'',type:TYPES[0],company:'',driver:''};
const OVERVIEW={total:486,available:210,onTrip:156,maintenance:36,inactive:84};
function dual(a,b){return <span className="fleet-dual"><strong>{a}</strong><small>{b}</small></span>}
function exportCsv(rows){const data=[['Plate','Reference','Type','Company','Driver','Status','Location','Last Trip'],...rows.map(r=>[r.plate,r.ref,r.type,r.company,r.driver,r.status,r.loc,r.trip])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='trukkas-fleet.csv';a.click();URL.revokeObjectURL(url)}

export function FleetManagement(){
 const navigate=useNavigate(),trucks=useCollection('trucks')||[],upload=useRef(null);
 const [q,setQ]=useState(''),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Types'),[company,setCompany]=useState('All Companies'),[location,setLocation]=useState('All Locations'),[sort,setSort]=useState('Newest'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[menu,setMenu]=useState(null),[addOpen,setAddOpen]=useState(false),[form,setForm]=useState(EMPTY),[toast,setToast]=useState('');
 const companies=['All Companies',...new Set(trucks.map(t=>t.company))],locations=['All Locations',...new Set(trucks.map(t=>t.state).filter(x=>x!=='—'))];
 const filtered=useMemo(()=>{const list=trucks.filter(t=>(status==='All Status'||t.status===status)&&(type==='All Types'||t.type===type)&&(company==='All Companies'||t.company===company)&&(location==='All Locations'||t.state===location)&&(!q||[t.plate,t.ref,t.company,t.driver,t.loc].some(v=>String(v).toLowerCase().includes(q.toLowerCase()))));return [...list].sort((a,b)=>sort==='Plate A–Z'?a.plate.localeCompare(b.plate):sort==='Company A–Z'?a.company.localeCompare(b.company):b.ref.localeCompare(a.ref))},[trucks,q,status,type,company,location,sort]);
 const paged=filtered.slice((page-1)*pageSize,page*pageSize);function reset(){setQ('');setStatus('All Status');setType('All Types');setCompany('All Companies');setLocation('All Locations');setPage(1)}function notify(s){setToast(s);setTimeout(()=>setToast(''),1700)}
 return <div className="fleet-page"><PageHeader crumbs={['Fleet','Fleet Management']} title="Fleet Management" description="Monitor and manage all trucks and fleet assets on the platform." actions={<><Button icon="plus" onClick={()=>setAddOpen(true)}>Add Truck</Button><Button variant="outline" icon="download" onClick={()=>upload.current?.click()}>Import Trucks</Button><input ref={upload} hidden type="file" accept=".csv,.xlsx" onChange={e=>{if(e.target.files[0])notify(`${e.target.files[0].name} imported successfully`)}}/><span className="fleet-menu-wrap"><Button variant="outline" iconRight="chevron-down" onClick={()=>setMenu(menu==='top'?null:'top')}>More Actions</Button>{menu==='top'&&<span className="fleet-dropdown"><DropdownMenu width={210} items={[{label:'Export Fleet',icon:'download',onClick:()=>{exportCsv(filtered);setMenu(null)}},{label:'Schedule Maintenance',icon:'wrench',onClick:()=>navigate('/maintenance')},{label:'Print Fleet List',icon:'printer',onClick:()=>window.print()}]}/></span>}</span></>}/>
 <div className="fleet-stats"><StatCard icon="truck" label="Total Trucks" value={OVERVIEW.total} delta="24" caption="from last month"/><StatCard icon="circle-check" tint="green" label="Available" value={OVERVIEW.available} caption="43.2% of total"/><StatCard icon="route" label="On Trip" value={OVERVIEW.onTrip} caption="32.1% of total"/><StatCard icon="wrench" tint="amber" label="In Maintenance" value={OVERVIEW.maintenance} caption="7.4% of total"/><StatCard icon="circle-x" tint="navy" label="Inactive" value={OVERVIEW.inactive} caption="17.3% of total"/></div>
 <Card pad="none"><div className="fleet-toolbar"><SearchField placeholder="Search by truck no., plate number, or company..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{['All Status',...STATUSES].map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}>{['All Types',...TYPES].map(x=><option key={x}>{x}</option>)}</select><select value={company} onChange={e=>{setCompany(e.target.value);setPage(1)}}>{companies.map(x=><option key={x}>{x}</option>)}</select><select value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}>{locations.map(x=><option key={x}>{x}</option>)}</select><Button variant="outline" icon="rotate-ccw" onClick={reset}>Reset</Button></div></Card>
 <div className="fleet-layout"><SectionCard title="Trucks" count={OVERVIEW.total} pad="none" action={<select className="fleet-sort" value={sort} onChange={e=>setSort(e.target.value)}>{['Newest','Plate A–Z','Company A–Z'].map(x=><option key={x}>{x}</option>)}</select>}><DataTable rows={paged} rowKey={r=>r.plate} onRowClick={r=>navigate('/fleet/'+encodeURIComponent(r.plate))} columns={[{key:'plate',header:'Truck / Plate No.',render:r=><span className="fleet-truck-cell"><span className="fleet-thumb">🚚</span>{dual(<span className="fleet-link">{r.plate}</span>,r.ref)}</span>},{key:'type',header:'Truck Type',render:r=>dual(r.type,r.tag)},{key:'company',header:'Truck Company',render:r=>dual(r.company,r.tc)},{key:'driver',header:'Driver',render:r=>dual(r.driver,r.dr)},{key:'status',header:'Status',render:r=><Badge dot>{r.status}</Badge>},{key:'loc',header:'Location',render:r=>dual(r.loc,r.state)},{key:'trip',header:'Last Trip',render:r=>dual(<span className="fleet-link">{r.trip}</span>,r.date)},{key:'x',header:'Actions',render:r=><span className="fleet-row-actions"><IconButton icon="eye" tone="outline" onClick={e=>{e.stopPropagation();navigate('/fleet/'+encodeURIComponent(r.plate))}}/><IconButton icon="ellipsis-vertical" tone="outline" onClick={e=>{e.stopPropagation();setMenu(menu===r.plate?null:r.plate)}}/>{menu===r.plate&&<span className="fleet-dropdown"><DropdownMenu width={205} items={[{label:'View Truck',icon:'eye',onClick:()=>navigate('/fleet/'+encodeURIComponent(r.plate))},{label:'Schedule Maintenance',icon:'wrench',onClick:()=>navigate('/maintenance?truck='+encodeURIComponent(r.plate))},{divider:true},...STATUSES.filter(x=>x!==r.status).map(x=>({label:`Mark as ${x}`,icon:'check',onClick:()=>{setTruckStatus(r.plate,x);setMenu(null);notify(`Truck marked ${x}`)}}))]}/></span>}</span>}]}/>{!paged.length&&<div className="fleet-empty">No trucks match the selected filters.</div>}<Pagination page={page} pageCount={Math.max(1,Math.ceil(filtered.length/pageSize))} pageSize={pageSize} total={filtered.length} onPage={p=>setPage(Math.max(1,Math.min(p,Math.max(1,Math.ceil(filtered.length/pageSize)))))} onPageSize={n=>{setPageSize(n);setPage(1)}}/></SectionCard>
 <aside className="fleet-rail"><SectionCard title="Fleet Overview"><div className="fleet-chart"><DonutChart size={145} thickness={20} centerValue="486" centerLabel="Total" data={[{label:'Available',value:210},{label:'On Trip',value:156},{label:'In Maintenance',value:36},{label:'Inactive',value:84}]}/><LegendList items={[{label:'Available',value:210},{label:'On Trip',value:156},{label:'In Maintenance',value:36},{label:'Inactive',value:84}]}/></div></SectionCard><SectionCard title="Truck Types" action={<button className="fleet-text-btn" onClick={()=>setType('All Types')}>View all</button>}><RankBarList numbered={false} items={[{label:'40FT Trailer',value:186,display:'186 (38.3%)'},{label:'20FT Container',value:132,display:'132 (27.2%)'},{label:'Flatbed',value:78,display:'78 (16.0%)'},{label:'40FT High Cube',value:45,display:'45 (9.3%)'},{label:'Tanker',value:28,display:'28 (5.8%)'}]}/></SectionCard><SectionCard title="Maintenance Alerts" action={<button className="fleet-text-btn" onClick={()=>navigate('/maintenance')}>View all</button>}><ListRow icon="clock" iconTint="amber" title="6 Trucks" subtitle="Maintenance due in next 7 days" onClick={()=>navigate('/maintenance')}/><ListRow icon="circle-alert" iconTint="red" title="3 Trucks" subtitle="Maintenance overdue" onClick={()=>navigate('/maintenance')}/><ListRow icon="wrench" title="36 Trucks" subtitle="Currently in maintenance" onClick={()=>navigate('/maintenance')}/></SectionCard><QuickActionsCard items={[{icon:'truck',label:'Add Truck',hint:'Register a new truck to the fleet',onClick:()=>setAddOpen(true)},{icon:'wrench',label:'Schedule Maintenance',hint:'Plan maintenance for a truck',onClick:()=>navigate('/maintenance')},{icon:'upload',label:'Bulk Upload',hint:'Upload truck data in bulk',onClick:()=>upload.current?.click()},{icon:'download',label:'Export Fleet',hint:'Download fleet data report',onClick:()=>exportCsv(filtered)}]}/></aside></div>
 <Modal open={addOpen} onClose={()=>{setAddOpen(false);setForm(EMPTY)}} title="Add Truck" description="Register a new truck to the fleet." footer={<><Button variant="outline" onClick={()=>setAddOpen(false)}>Cancel</Button><Button disabled={!form.plate||!form.company||!form.driver} onClick={async()=>{await addTruck({plate:form.plate.toUpperCase(),ref:`TRK-2026-${String(Date.now()).slice(-6)}`,type:form.type,tag:form.type.split(' ').slice(-1)[0],company:form.company,driver:form.driver,tc:`TC-${String(Date.now()).slice(-6)}`,dr:`DR-${String(Date.now()+1).slice(-6)}`});setAddOpen(false);setForm(EMPTY);notify('Truck added successfully')}}>Save Truck</Button></>}><div className="fleet-form"><TextField label="Plate Number" required placeholder="e.g. KJA-123-XD" value={form.plate} onChange={e=>setForm({...form,plate:e.target.value})}/><Select label="Truck Type" value={form.type} options={TYPES} onChange={e=>setForm({...form,type:e.target.value})}/><TextField label="Truck Company" required value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><TextField label="Driver Name" required value={form.driver} onChange={e=>setForm({...form,driver:e.target.value})}/></div></Modal>{toast&&<div className="maint-toast">{toast}</div>}</div>
}
