'use client';

import { useEffect, useState } from 'react';
import { useNavigate, useParams } from '../router.js';
import { PageHeader, Button, Card, SectionCard, Badge, Icon, Switch } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { createKnowledgeArticle, updateKnowledgeArticle } from '../mock/api.js';
import { knowledgeCategories } from '../mock/fixtures/support.js';
import './Support.css';

const blank={title:'',category:'',subcategory:'',status:'Draft',summary:'',content:'',visibility:'Public',featured:false,feedback:true,related:true,seoTitle:'',metaDescription:'',tags:[],attachments:[]};
export function KnowledgeArticleForm({editing=false}){
 const navigate=useNavigate();const {articleId}=useParams();const articles=useCollection('knowledgeArticles')||[];const existing=articles.find(a=>a.id===articleId);const [form,setForm]=useState(blank);const [tag,setTag]=useState('');const [saving,setSaving]=useState(false);const [toast,setToast]=useState('');
 useEffect(()=>{if(editing&&existing)setForm({...blank,...existing})},[editing,existing]);
 function change(key,value){setForm(f=>({...f,[key]:value}))} function addTag(e){if(e.key==='Enter'&&tag.trim()){e.preventDefault();if(!form.tags.includes(tag.trim()))change('tags',[...form.tags,tag.trim()]);setTag('')}}
 function addFiles(files){change('attachments',[...form.attachments,...Array.from(files).map(f=>({name:f.name,size:`${Math.ceil(f.size/1024)} KB`}))])}
 async function save(status){if(!form.title.trim()||!form.category||!form.summary.trim()||!form.content.trim()){setToast('Complete all required fields');setTimeout(()=>setToast(''),1800);return}setSaving(true);let record;if(editing)record=await updateKnowledgeArticle(articleId,{...form,status});else record=await createKnowledgeArticle({...form,status});setSaving(false);navigate(status==='Published'?'/knowledge-base/'+record.id:'/knowledge-base')}
 if(editing&&!existing)return <Card>Article not found.</Card>;
 return <div className="support-page">
  <PageHeader crumbs={['Support System','Knowledge Base',editing?'Edit Article':'New Article']} title={editing?'Edit Article':'New Article'} description={editing?'Update this knowledge base article.':'Create a new knowledge base article to help users find answers.'}/>
  <div className="article-form-grid"><div className="article-form-main"><Card className="form-card">
   <label><span className="field-label">Article Title <em>*</em></span><div style={{position:'relative'}}><input className="plain-input" maxLength={150} placeholder="Enter a clear and descriptive title" value={form.title} onChange={e=>change('title',e.target.value)}/><small className="tk-meta" style={{position:'absolute',right:9,top:11}}>{form.title.length}/150</small></div></label>
   <div className="form-row"><label><span className="field-label">Category <em>*</em></span><select className="plain-input" value={form.category} onChange={e=>change('category',e.target.value)}><option value="">Select a category</option>{knowledgeCategories.map(([x])=><option key={x}>{x}</option>)}</select></label><label><span className="field-label">Subcategory</span><input className="plain-input" placeholder="Select a subcategory" value={form.subcategory} onChange={e=>change('subcategory',e.target.value)}/></label><label><span className="field-label">Article Status <em>*</em></span><select className="plain-input" value={form.status} onChange={e=>change('status',e.target.value)}><option>Draft</option><option>Published</option><option>Archived</option></select></label></div>
   <label><span className="field-label">Short Description (Summary) <em>*</em></span><div style={{position:'relative'}}><textarea className="plain-input summary-input" maxLength={250} placeholder="Write a brief summary of what this article is about..." value={form.summary} onChange={e=>change('summary',e.target.value)}/><small className="tk-meta" style={{position:'absolute',right:9,bottom:8}}>{form.summary.length}/250</small></div></label>
   <label><span className="field-label">Article Content <em>*</em></span><div className="article-editor"><div className="editor-tools"><button type="button" title="Paragraph">Paragraph⌄</button>{[['bold','B'],['italic','I'],['underline','U'],['strikethrough','S'],['code-2','</>'],['list','☷'],['align-left','≡'],['link','🔗'],['image','▧'],['table','▦']].map(([name,label])=><button type="button" key={name} title={name} onClick={()=>document.execCommand(name==='bold'||name==='italic'||name==='underline'?name:'insertText',false,'')}>{label}</button>)}<span style={{flex:1}}/><button type="button" onClick={()=>setToast('Preview is available after saving')}>Preview</button></div><textarea className="editor-area" placeholder="Write your article content here..." value={form.content} onChange={e=>change('content',e.target.value)}/><div className="tk-meta" style={{textAlign:'right',padding:'0 10px 8px'}}>{form.content.trim()?form.content.trim().split(/\s+/).length:0} words</div></div></label>
   <label><span className="field-label">Attachments</span><input id="kb-files" type="file" multiple hidden onChange={e=>addFiles(e.target.files)}/><span className="dropzone" onClick={()=>document.getElementById('kb-files').click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><Icon name="cloud-upload" size={22}/><br/><strong>Drag and drop files here or <span className="support-link">Browse</span></strong><br/><span className="tk-meta">Supports: PDF, DOC, DOCX, PNG, JPG (Max 10MB)</span></span>{form.attachments.map((a,i)=><span className="tag-chip" key={i}><Icon name="paperclip" size={12}/>{a.name}<button onClick={()=>change('attachments',form.attachments.filter((_,n)=>n!==i))}>×</button></span>)}</label>
   <label><span className="field-label">Add Tags</span><input className="plain-input" placeholder="Type and press Enter to add tags" value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={addTag}/><div className="tag-list">{form.tags.map(t=><span className="tag-chip" key={t}>{t}<button onClick={()=>change('tags',form.tags.filter(x=>x!==t))}>×</button></span>)}</div><small className="tk-meta">Tags help users find related articles easily.</small></label>
  </Card><Card className="sticky-actions"><Button variant="outline" style={{marginRight:'auto'}} onClick={()=>navigate('/knowledge-base')}>Cancel</Button><Button variant="outline" icon="save" disabled={saving} onClick={()=>save('Draft')}>Save as Draft</Button><Button icon="send" disabled={saving} onClick={()=>save('Published')}>Publish Article</Button></Card></div>
  <div className="article-form-rail"><SectionCard title="Publish"><div className="rail-controls"><div className="info-row"><label>Status</label><span><Badge tone={form.status==='Published'?'success':'neutral'} dot>{form.status}</Badge></span></div><small className="tk-meta">Save as draft or publish when ready.</small><div><span className="field-label">Visibility</span><label className="radio-row"><input type="radio" checked={form.visibility==='Public'} onChange={()=>change('visibility','Public')}/><span><strong>Public</strong><small className="tk-meta" style={{display:'block'}}>Visible to all users</small></span></label><label className="radio-row" style={{marginTop:10}}><input type="radio" checked={form.visibility==='Internal'} onChange={()=>change('visibility','Internal')}/><span><strong>Internal</strong><small className="tk-meta" style={{display:'block'}}>Only visible to agents and admins</small></span></label></div><div><span className="field-label">Published By</span><span className="support-person"><span style={{width:28,height:28,borderRadius:'50%',background:'var(--tk-navy)',color:'#fff',display:'grid',placeItems:'center'}}>TA</span><span><strong>Trukkas Admin</strong><small className="tk-meta" style={{display:'block'}}>Super Admin</small></span></span></div><div style={{display:'flex',gap:10}}><Button variant="outline" style={{flex:1}} onClick={()=>save('Draft')}>Save as Draft</Button><Button style={{flex:1}} onClick={()=>save('Published')}>Publish Article</Button></div></div></SectionCard>
   <SectionCard title="Article Settings"><div className="settings-row"><Icon name="star" size={16} color="var(--tk-blue)"/><span><strong>Featured Article</strong><small>Display this article on the homepage</small></span><Switch checked={form.featured} onChange={v=>change('featured',v)}/></div><div className="settings-row"><Icon name="message-square" size={16} color="var(--tk-blue)"/><span><strong>Allow Feedback</strong><small>Allow users to rate and give feedback</small></span><Switch checked={form.feedback} onChange={v=>change('feedback',v)}/></div><div className="settings-row"><Icon name="link" size={16} color="var(--tk-blue)"/><span><strong>Related Articles</strong><small>Show related articles at the end</small></span><Switch checked={form.related} onChange={v=>change('related',v)}/></div></SectionCard>
   <SectionCard title="SEO Settings"><label><span className="field-label">SEO Title</span><input className="plain-input" maxLength={60} placeholder="Enter SEO title (optional)" value={form.seoTitle} onChange={e=>change('seoTitle',e.target.value)}/><small className="tk-meta" style={{float:'right'}}>{form.seoTitle.length}/60</small></label><label style={{display:'block',marginTop:16}}><span className="field-label">Meta Description</span><textarea className="plain-input summary-input" maxLength={160} placeholder="Enter meta description (optional)" value={form.metaDescription} onChange={e=>change('metaDescription',e.target.value)}/><small className="tk-meta" style={{float:'right'}}>{form.metaDescription.length}/160</small></label></SectionCard>
  </div></div>{toast&&<div className="toast">{toast}</div>}
 </div>
}
