'use client';

import { useMemo, useState } from 'react';
import { useNavigate } from '../router.js';
import { PageHeader, Button, StatCard, SectionCard, Card, Tabs, SearchField, DataTable, Pagination, Badge, Avatar, Icon } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { knowledgeCategories } from '../mock/fixtures/support.js';
import './Support.css';

const PAGE_SIZE=8; const catTone={'Trips & Jobs':'info','Container Triangulation':'purple','Provisional Release':'orange','Fleet Management':'info',Finance:'success','Live Tracking':'teal',Pricing:'danger',General:'neutral'};
function exportCsv(rows){const head=['Title','Category','Author','Status','Views','Helpful','Last Updated'];const csv=[head,...rows.map(r=>[r.title,r.category,r.author,r.status,r.views??'',r.helpful??'',r.updated])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='knowledge-base.csv';a.click();URL.revokeObjectURL(u)}

export function KnowledgeBase(){
 const navigate=useNavigate();const articles=useCollection('knowledgeArticles')||[];const [tab,setTab]=useState('All Articles');const [q,setQ]=useState('');const [category,setCategory]=useState('All');const [status,setStatus]=useState('All');const [author,setAuthor]=useState('All');const [page,setPage]=useState(1);const [tip,setTip]=useState(true);const [selected,setSelected]=useState([]);
 const authors=[...new Set(articles.map(a=>a.author))];
 const filtered=useMemo(()=>articles.filter(a=>(tab==='All Articles'||a.status===(tab==='Drafts'?'Draft':tab==='Published'?'Published':'Archived'))&&(category==='All'||a.category===category)&&(status==='All'||a.status===status)&&(author==='All'||a.author===author)&&(!q||[a.title,a.summary,a.category,a.author].some(v=>v.toLowerCase().includes(q.toLowerCase())))),[articles,tab,q,category,status,author]);
 const paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE); const pub=articles.filter(a=>a.status==='Published').length;const draft=articles.filter(a=>a.status==='Draft').length;const totalViews=articles.reduce((s,a)=>s+(a.views||0),0);
 return <div className="support-page">
  <PageHeader crumbs={['Support System','Knowledge Base']} title="Knowledge Base" description="Create, organize and manage helpful articles for users." actions={<Button icon="plus" onClick={()=>navigate('/knowledge-base/new')}>New Article</Button>}/>
  <div className="support-stats"><StatCard icon="book-open" label="Total Articles" value="186" delta="18%" caption="from last 7 days"/><StatCard icon="clipboard-check" tint="green" label="Published Articles" value="142" delta="15%" caption="from last 7 days"/><StatCard icon="file-pen-line" tint="amber" label="Draft Articles" value="32" delta="5%" direction="down" caption="from last 7 days"/><StatCard icon="chart-no-axes-column-increasing" label="Views (This Month)" value="4,286" delta="24%" caption="from last 7 days"/><StatCard icon="star" label="Helpful Ratings" value="92%" delta="6%" caption="from last 7 days"/></div>
  <div className="support-layout"><SectionCard title="" pad="none">
   <Tabs value={tab} onChange={v=>{setTab(v);setPage(1)}} items={['All Articles','Published','Drafts','Archived']} style={{padding:'0 16px'}}/>
   <div className="support-toolbar"><SearchField style={{flex:1,minWidth:220}} placeholder="Search articles..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select className="support-select" aria-label="Category filter" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option>All</option>{knowledgeCategories.map(([x])=><option key={x}>{x}</option>)}</select><select className="support-select" aria-label="Status filter" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{['All','Published','Draft','Archived'].map(x=><option key={x}>{x}</option>)}</select><select className="support-select" aria-label="Author filter" value={author} onChange={e=>{setAuthor(e.target.value);setPage(1)}}><option>All</option>{authors.map(x=><option key={x}>{x}</option>)}</select><Button variant="outline" icon="sliders-horizontal" onClick={()=>{setCategory('All');setStatus('All');setAuthor('All')}}>Reset</Button><Button variant="outline" icon="download" onClick={()=>exportCsv(filtered)}>Export</Button></div>
   {selected.length>0&&<div style={{padding:'9px 16px',background:'var(--tk-blue-soft)',color:'var(--tk-blue)',fontSize:12,display:'flex',alignItems:'center',gap:10}}><strong>{selected.length} selected</strong><Button size="sm" variant="outline" icon="download" onClick={()=>exportCsv(articles.filter(a=>selected.includes(a.id)))}>Export selected</Button><Button size="sm" variant="ghost" onClick={()=>setSelected([])}>Clear</Button></div>}
   <DataTable selectable selected={selected} onSelect={setSelected} rows={paged} rowKey={r=>r.id} onRowClick={r=>navigate('/knowledge-base/'+r.id)} columns={[
    {key:'title',header:'Title',render:r=><span style={{display:'flex',gap:9,alignItems:'center'}}><Icon name="file-text" size={14} color="var(--tk-blue)"/><span className="support-title-cell"><strong>{r.title}</strong><small>{r.summary}</small></span></span>},
    {key:'category',header:'Category',render:r=><Badge tone={catTone[r.category]}>{r.category}</Badge>},
    {key:'author',header:'Author',render:r=><span className="support-person"><Avatar name={r.author} size={24}/><span>{r.author}</span></span>},
    {key:'status',header:'Status',render:r=><Badge tone={r.status==='Published'?'success':'info'}>{r.status}</Badge>},
    {key:'views',header:'Views',render:r=>r.views?.toLocaleString()??'—'},
    {key:'helpful',header:'Helpful',render:r=>r.helpful?<span style={{color:'var(--tk-success)',whiteSpace:'nowrap'}}><Icon name="thumbs-up" size={12}/> {r.helpful}%</span>:'—'},
    {key:'updated',header:'Last Updated',render:r=><span style={{display:'grid',whiteSpace:'nowrap'}}><span>{r.updated}</span><small className="tk-meta">{r.time}</small></span>},
    {key:'actions',header:'Actions',width:42,render:r=><button className="support-row-action" onClick={e=>{e.stopPropagation();navigate('/knowledge-base/'+r.id)}}><Icon name="ellipsis" size={16}/></button>},
   ]}/><Pagination page={page} pageCount={Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))} total={filtered.length||0} pageSize={PAGE_SIZE} onPage={p=>setPage(Math.min(Math.max(p,1),Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))))}/>
  </SectionCard><div className="support-rail">
   <SectionCard title="Categories" action={<button className="support-link" style={{border:0,background:'none'}} onClick={()=>{setCategory('All');setPage(1);window.scrollTo({top:0,behavior:'smooth'})}}>View all</button>}>{knowledgeCategories.map(([name,count])=><button className="kb-category" style={{width:'100%',border:0,background:'transparent',cursor:'pointer',textAlign:'left'}} key={name} onClick={()=>{setCategory(name);setPage(1);window.scrollTo({top:0,behavior:'smooth'})}}><span className="cat-icon"><Icon name="book-open" size={13}/></span><strong>{name}</strong><b>{count}</b></button>)}</SectionCard>
   <SectionCard title="Popular Articles" action={<button className="support-link" style={{border:0,background:'none'}} onClick={()=>{setQ('');setCategory('All');setStatus('Published');setPage(1)}}>View all</button>}>{[...articles].sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,5).map(a=><button className="support-action" key={a.id} onClick={()=>navigate('/knowledge-base/'+a.id)}><span className="ico"><Icon name="eye" size={13}/></span><span><strong>{a.title}</strong><small>{a.views?.toLocaleString()} views</small></span></button>)}</SectionCard>
   <SectionCard title={<span>Article Feedback <small>(This Month)</small></span>}><div className="feedback-wrap"><div className="feedback-ring"/><div className="feedback-legend"><span><i style={{color:'var(--tk-success)'}}>● Helpful</i><b>92% (1,248)</b></span><span><i style={{color:'var(--tk-danger)'}}>● Not Helpful</i><b>5% (68)</b></span><span><i style={{color:'var(--tk-warning)'}}>● Neutral</i><b>3% (41)</b></span></div></div></SectionCard>
  </div></div>
  {tip&&<Card tone="cool"><div className="kb-tip"><span className="bulb"><Icon name="lightbulb" size={22}/></span><span style={{flex:1}}><strong>Help users find answers faster</strong><small>Keep your knowledge base up to date and organized. Well-maintained articles reduce support tickets by up to 40%.</small></span><Button variant="outline" onClick={()=>alert('Analytics dashboard is coming soon.')}>View Analytics</Button><Button variant="ghost" icon="x" aria-label="Dismiss tip" onClick={()=>setTip(false)}/></div></Card>}
 </div>
}
