'use client';

import { useState } from 'react';
import { useNavigate, useParams } from '../router.js';
import { PageHeader, Button, Card, SectionCard, Badge, Avatar, Icon, DropdownMenu } from '../ds.js';
import { useCollection } from '../mock/useCollection.js';
import { createKnowledgeArticle } from '../mock/api.js';
import './Support.css';

function downloadArticle(a){const blob=new Blob([`${a.title}\n\n${a.summary}\n\n${a.content||'See the complete guide in the Trukkas admin knowledge base.'}`],{type:'text/plain'});const u=URL.createObjectURL(blob);const x=document.createElement('a');x.href=u;x.download=a.id+'.txt';x.click();URL.revokeObjectURL(u)}
export function KnowledgeArticleDetail(){
 const {articleId}=useParams();const navigate=useNavigate();const articles=useCollection('knowledgeArticles')||[];const article=articles.find(a=>a.id===articleId);const [menu,setMenu]=useState(false);const [vote,setVote]=useState('');const [toast,setToast]=useState('');function notify(x){setToast(x);setTimeout(()=>setToast(''),1800)}
 if(!article)return <Card><p>Article not found.</p><Button variant="outline" onClick={()=>navigate('/knowledge-base')}>Back to Articles</Button></Card>;
 const related=articles.filter(a=>a.id!==article.id&&a.status==='Published').slice(0,5);
 async function duplicate(){const {id:unused,...source}=article;const copy=await createKnowledgeArticle({...source,title:article.title+' (Copy)',status:'Draft'});notify('Article duplicated');navigate('/knowledge-base/'+copy.id+'/edit')}
 return <div className="support-page"><PageHeader crumbs={['Support System','Knowledge Base',article.title]} title={article.title} meta={null} actions={<><Button variant="outline" icon="arrow-left" onClick={()=>navigate('/knowledge-base')}>Back to Articles</Button><Button variant="outline" icon="pencil" onClick={()=>navigate('/knowledge-base/'+article.id+'/edit')}>Edit Article</Button><span style={{position:'relative'}}><Button variant="outline" icon="ellipsis" onClick={()=>setMenu(!menu)}>More Actions</Button>{menu&&<span style={{position:'absolute',right:0,top:44,zIndex:30}}><DropdownMenu width={220} items={[{label:'Duplicate Article',icon:'copy',onClick:duplicate},{label:'Print Article',icon:'printer',onClick:()=>window.print()},{label:'Export Article',icon:'download',onClick:()=>downloadArticle(article)},{label:'Share Article',icon:'share-2',onClick:()=>{navigator.clipboard?.writeText(location.href);notify('Article link copied')}}]}/></span>}</span></>}/>
  <div className="article-grid"><div className="article-main"><div className="article-head-meta"><Badge tone="success">{article.status}</Badge><span><Icon name="tag" size={14}/><Badge tone="info">{article.category}</Badge></span><span><Avatar name={article.author} size={24}/>{article.author}</span><span><Icon name="calendar-days" size={14}/>{article.updated}</span><span><Icon name="eye" size={14}/>{(article.views||0).toLocaleString()} views</span><span style={{color:'var(--tk-success)'}}><Icon name="thumbs-up" size={14}/>{article.helpful||0}% helpful</span></div>
   <div className="article-content"><p>{article.summary.replace(/\.\.\.$/,'.')} This guide will walk you through all the required details and settings to get your trip created successfully.</p><hr style={{border:0,borderTop:'1px solid var(--tk-line)',margin:'16px 0'}}/><h2>1. Navigate to Trips</h2><p>From your dashboard, click on the <b>Trips &amp; Jobs</b> menu and select <b>Trips</b>.</p><div className="article-shot"><div className="article-shot-top"><Icon name="menu" size={13}/><span style={{fontSize:10}}>Trips &amp; Jobs</span><span style={{flex:1}}/><Button size="sm" icon="plus">New Trip</Button></div><div className="article-shot-body"><div className="article-shot-nav"><strong>Trukkas</strong><div>Dashboard</div><div className="active">Jobs &amp; Trips</div><div>Dispatch Center</div><div>Live Tracking</div><div>Fleet Management</div></div><div className="article-shot-main"><b>Trips</b><div style={{display:'flex',gap:14,fontSize:8,marginTop:8,color:'var(--tk-blue)'}}>All Trips <span>Ongoing</span><span>Completed</span></div><div className="article-shot-table"><div><b>Trip ID</b><b>Route</b><b>Truck</b><b>Status</b></div><div><span>TRP-2024-00124</span><span>Lagos → Tema</span><span>TKT 456 XA</span><span>Ongoing</span></div><div><span>TRP-2024-00123</span><span>Apapa → Kano</span><span>TKT 782 AB</span><span>Pending</span></div><div><span>TRP-2024-00122</span><span>Onne → Kigali</span><span>TKT 992 KL</span><span>Draft</span></div></div></div></div></div>
   <h2>2. Click on “New Trip”</h2><p>Click the <b>+ New Trip</b> button on the top right corner.</p><div className="tip-box"><Icon name="lightbulb" size={18} color="var(--tk-blue)"/><span><b>Tip:</b> You must have the necessary permissions to create a new trip.</span></div><h2>3. Fill in Trip Details</h2><p>Provide the required trip information in the create trip form.</p><ul><li><b>Trip Type:</b> Select the appropriate trip type.</li><li><b>Origin:</b> Select the starting location.</li><li><b>Destination:</b> Select the destination.</li><li><b>Cargo Type:</b> Choose the type of cargo.</li><li><b>Truck (Optional):</b> Assign a truck if available.</li><li><b>Expected Date:</b> Select the expected start date.</li></ul><h2>4. Review &amp; Create</h2><p>Review all the details and click <b>Create Trip</b> to save your trip.</p>
   <div className="helpful-box"><span className="bulb" style={{width:36,height:36,borderRadius:'50%',background:'var(--tk-blue-soft)',display:'grid',placeItems:'center'}}><Icon name="lightbulb" size={18} color="var(--tk-blue)"/></span><div><strong>Was this article helpful?</strong><small className="tk-meta" style={{display:'block'}}>96% of users found this helpful</small></div><Button variant={vote==='yes'?'primary':'outline'} icon="thumbs-up" onClick={()=>{setVote('yes');notify('Thanks for your feedback!')}}>Yes, helpful</Button><Button variant={vote==='no'?'danger':'outline'} icon="thumbs-down" onClick={()=>{setVote('no');notify('Thanks — we’ll improve this article.')}}>No, not helpful</Button></div></div>
  </div><div className="support-rail"><SectionCard title="Article Information"><div className="info-list"><div className="info-row"><label>Status</label><span><Badge tone="success" dot>{article.status}</Badge></span></div><div className="info-row"><label>Visibility</label><span><Icon name="globe-2" size={13}/> {article.visibility}</span></div><div className="info-row"><label>Category</label><span><Badge tone="info">{article.category}</Badge></span></div><div className="info-row"><label>Subcategory</label><span>{article.subcategory}</span></div><div className="info-row"><label>Author</label><span className="support-person"><Avatar name={article.author} size={24}/>{article.author}</span></div><div className="info-row"><label>Published</label><span>{article.updated}, {article.time}</span></div><div className="info-row"><label>Last Updated</label><span>{article.updated}, {article.time}</span></div></div></SectionCard>
   <SectionCard title="Article Tools"><Action icon="pencil" label="Edit Article" onClick={()=>navigate('/knowledge-base/'+article.id+'/edit')}/><Action icon="copy" label="Duplicate Article" onClick={duplicate}/><Action icon="printer" label="Print Article" onClick={()=>window.print()}/><Action icon="download" label="Export Article" onClick={()=>downloadArticle(article)}/><Action icon="share-2" label="Share Article" onClick={()=>{navigator.clipboard?.writeText(location.href);notify('Article link copied')}}/></SectionCard>
   <SectionCard title="Related Articles" action={<button className="support-link" style={{border:0,background:'none'}} onClick={()=>navigate('/knowledge-base')}>View all</button>}>{related.map(a=><button className="support-action" key={a.id} onClick={()=>navigate('/knowledge-base/'+a.id)}><span className="ico"><Icon name="file-text" size={13}/></span><span><strong>{a.title}</strong><small>{a.views?.toLocaleString()} views</small></span></button>)}</SectionCard>
   <SectionCard title="Need More Help?"><p className="tk-meta">Can’t find what you’re looking for?</p><Button variant="outline" fullWidth icon="life-buoy" iconRight="arrow-right" onClick={()=>navigate('/tickets')}>Create a Support Ticket</Button></SectionCard>
  </div></div>{toast&&<div className="toast">{toast}</div>}</div>
}
function Action({icon,label,onClick}){return <button className="support-action" onClick={onClick}><span className="ico"><Icon name={icon} size={14}/></span><span><strong>{label}</strong></span></button>}
