"use client";
import { useMemo, useState } from "react";
import { useNavigate } from "../router.js";
import { Avatar, Badge, Button, Card, DataTable, DropdownMenu, Icon, IconButton, Modal, Pagination, SearchField, Select, StatCard, Tabs, TextField } from "../ds.js";
import { useCollection } from "../mock/useCollection.js";
import { companyStats } from "../mock/fixtures/companies.js";
import { addCompany, setCompanyStatus, setCompanyVerification } from "../mock/api.js";
import "./TruckingCompanies.css";

const tone = { Active: "success", Inactive: "neutral", Suspended: "danger", Verified: "success", Pending: "warning", Rejected: "danger" };
const blank = { name: "", regNo: "", contactName: "", contactPhone: "", contactEmail: "", location: "" };
function downloadCsv(rows) {
  const fields = ["name", "regNo", "contactName", "contactPhone", "contactEmail", "location", "trucks", "drivers", "status", "verification"];
  const csv = [fields.join(","), ...rows.map((row) => fields.map((field) => `"${String(row[field] ?? "").replaceAll('"', '""')}"`).join(","))].join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = "trucking-companies.csv"; anchor.click(); URL.revokeObjectURL(url);
}

export function TruckCompanies() {
  const navigate = useNavigate(), companies = useCollection("companies") || [];
  const [tab, setTab] = useState("All Companies"), [query, setQuery] = useState(""), [status, setStatus] = useState("All Statuses"), [location, setLocation] = useState("All Locations"), [fleet, setFleet] = useState("All Fleet Sizes"), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(10), [selected, setSelected] = useState([]), [menuFor, setMenuFor] = useState(null), [addOpen, setAddOpen] = useState(false), [form, setForm] = useState(blank);
  const locations = useMemo(() => [...new Set(companies.map((company) => company.location))], [companies]);
  const filtered = useMemo(() => companies.filter((company) => {
    const needle = query.toLowerCase();
    const queryMatch = !needle || [company.name, company.regNo, company.contactName, company.contactPhone, company.contactEmail].some((value) => value?.toLowerCase().includes(needle));
    const tabMatch = tab === "All Companies" || (tab === "Pending Review" ? company.verification === "Pending" : company.verification === tab || company.status === tab);
    const fleetMatch = fleet === "All Fleet Sizes" || (fleet === "1–15 trucks" ? company.trucks <= 15 : fleet === "16–30 trucks" ? company.trucks >= 16 && company.trucks <= 30 : company.trucks > 30);
    return queryMatch && tabMatch && (status === "All Statuses" || company.status === status) && (location === "All Locations" || company.location === location) && fleetMatch;
  }), [companies, fleet, location, query, status, tab]);
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const topCompanies = [...companies].filter((company) => company.performance != null).sort((a, b) => b.performance - a.performance).slice(0, 5);
  const tabs = [{ value: "All Companies", label: "All Companies", count: companyStats.totalCompanies }, { value: "Pending Review", label: "Pending Review", count: 18 }, { value: "Verified", label: "Verified", count: companyStats.verifiedCompanies }, { value: "Suspended", label: "Suspended", count: 6 }, { value: "Rejected", label: "Rejected", count: 4 }];
  async function saveCompany() { if (!form.name || !form.regNo) return; await addCompany({ ...form, id: `TC-${Date.now()}`, trucks: 0, drivers: 0, status: "Active", verification: "Pending", performance: null, joined: "Sep 14, 2026" }); setForm(blank); setAddOpen(false); }

  return <div className="tc-page">
    <div className="tc-title-row"><div><span className="tc-breadcrumb">Companies <Icon name="chevron-right" size={13}/> Trucking Companies</span><h1 className="tk-display">Trucking Companies</h1><p className="tk-body">Review, verify and manage all registered trucking companies on Trukkas.</p></div><div className="tc-title-actions"><Button variant="outline" icon="download" onClick={() => downloadCsv(filtered)}>Export</Button><Button icon="plus" onClick={() => setAddOpen(true)}>Add Company</Button></div></div>
    <div className="tc-stat-grid tc-stat-grid-primary">
      <StatCard icon="building-2" label="Total Companies" value={companyStats.totalCompanies} delta="18%" caption="vs last month"/><StatCard icon="truck" tint="green" label="Active Companies" value={companyStats.activeCompanies} delta="16%" caption="vs last month"/><StatCard icon="shield-check" label="Verified Companies" value={companyStats.verifiedCompanies} delta="21%" caption="vs last month"/><StatCard icon="hourglass" tint="amber" label="Pending Review" value="18" delta="12%" direction="down" caption="vs last month"/><StatCard icon="ban" tint="red" label="Suspended Companies" value="6" delta="50%" direction="down" caption="vs last month"/>
    </div>
    <div className="tc-stat-grid tc-stat-grid-secondary"><StatCard icon="truck" tint="navy" label="Total Trucks" value={companyStats.totalTrucks.toLocaleString()} delta="14%" caption="vs last month"/><StatCard icon="users" label="Total Drivers" value={companyStats.totalDrivers.toLocaleString()} delta="17%" caption="vs last month"/><StatCard icon="truck" tint="green" label="Active Trucks" value={companyStats.activeTrucks.toLocaleString()} delta="19%" caption="vs last month"/><StatCard icon="wallet" tint="amber" label="Paid Out Amount" value="₦48,750,000" delta="28%" caption="vs last month"/></div>
    <Tabs value={tab} onChange={(value) => { setTab(value); setPage(1); }} items={tabs}/>
    <Card style={{ padding: "var(--tk-space-3)" }}><div className="tc-filters"><SearchField value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search by company name, RC number, email, phone..."/><Select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} options={["All Statuses", "Active", "Inactive", "Suspended"]}/><Select value={location} onChange={(event) => { setLocation(event.target.value); setPage(1); }} options={["All Locations", ...locations]}/><Select value={fleet} onChange={(event) => { setFleet(event.target.value); setPage(1); }} options={["All Fleet Sizes", "1–15 trucks", "16–30 trucks", "31+ trucks"]}/><Button variant="outline" icon="sliders-horizontal" onClick={() => { setStatus("All Statuses"); setLocation("All Locations"); setFleet("All Fleet Sizes"); }}>Filters</Button></div></Card>
    <div className="tc-content-grid"><Card pad="none"><DataTable rows={visible} rowKey={(row) => row.id} selectable selected={selected} onSelect={setSelected} onRowClick={(row) => navigate(`/companies/${row.id}`)} coloredHeader columns={[
      { key: "company", header: "Company", render: (row) => <span className="tc-company-cell"><Avatar name={row.name} size={36} square/><span><strong>{row.name}</strong><small>{row.regNo}</small></span></span> },
      { key: "contact", header: "Contact Person", render: (row) => <span className="tc-two-line"><strong>{row.contactName}</strong><small>{row.contactPhone}</small></span> }, { key: "location", header: "Location" },
      { key: "trucks", header: "Fleet", render: (row) => <button className="tc-link" onClick={(event) => { event.stopPropagation(); navigate(`/companies/${row.id}?tab=trucks`); }}>{row.trucks}</button> }, { key: "drivers", header: "Drivers" },
      { key: "status", header: "Status", render: (row) => <Badge dot tone={tone[row.status]}>{row.status}</Badge> }, { key: "verification", header: "Verification", render: (row) => <Badge dot tone={tone[row.verification]}>{row.verification}</Badge> }, { key: "joined", header: "Joined On" },
      { key: "actions", header: "Actions", width: 66, render: (row) => <span className="tc-menu" onClick={(event) => event.stopPropagation()}><IconButton icon="ellipsis" onClick={() => setMenuFor(menuFor === row.id ? null : row.id)}/>{menuFor === row.id && <span className="tc-dropdown"><DropdownMenu width={210} items={[{ label: "View company", icon: "eye", onClick: () => navigate(`/companies/${row.id}`) }, { label: "Open fleet", icon: "truck", onClick: () => navigate(`/companies/${row.id}?tab=trucks`) }, { divider: true }, { label: row.verification === "Verified" ? "Mark pending" : "Verify company", icon: "shield-check", onClick: () => { setCompanyVerification(row.id, row.verification === "Verified" ? "Pending" : "Verified"); setMenuFor(null); } }, { label: row.status === "Suspended" ? "Reactivate" : "Suspend", icon: "ban", tone: row.status === "Suspended" ? undefined : "danger", onClick: () => { setCompanyStatus(row.id, row.status === "Suspended" ? "Active" : "Suspended"); setMenuFor(null); } }]}/></span>}</span> }
    ]}/><Pagination page={page} pageCount={Math.max(1, Math.ceil(filtered.length / pageSize))} pageSize={pageSize} total={filtered.length} onPage={(next) => setPage(Math.min(Math.max(next, 1), Math.max(1, Math.ceil(filtered.length / pageSize))))} onPageSize={(size) => { setPageSize(size); setPage(1); }}/></Card>
      <aside className="tc-rail"><Card><h2 className="tk-section">Company Overview</h2><div className="tc-rail-intro"><span><Icon name="building-2" size={22}/></span><p className="tk-meta">Review company registration, fleet, drivers, documents and compliance in one place.</p></div><div className="tc-summary-list">{[["building-2", "Total Companies", companyStats.totalCompanies], ["truck", "Active Companies", companyStats.activeCompanies], ["shield-check", "Verified Companies", companyStats.verifiedCompanies], ["hourglass", "Pending Review", 18], ["ban", "Suspended Companies", 6], ["truck", "Total Trucks", companyStats.totalTrucks.toLocaleString()], ["users", "Total Drivers", companyStats.totalDrivers.toLocaleString()], ["wallet", "Paid Out Amount", "₦48,750,000"]].map(([icon, label, value]) => <div key={label}><Icon name={icon} size={15}/><span>{label}</span><strong>{value}</strong></div>)}</div></Card>
      <Card><div className="tc-card-head"><h2 className="tk-section">Top Performing Companies</h2><button>View All</button></div><ol className="tc-ranked">{topCompanies.map((company) => <li key={company.id}><button onClick={() => navigate(`/companies/${company.id}`)}>{company.name}</button><strong>{company.performance}%</strong></li>)}</ol></Card>
      <Card><div className="tc-card-head"><h2 className="tk-section">Recent Registrations</h2><button>View All</button></div><div className="tc-recent">{companies.slice(-5).reverse().map((company) => <button key={company.id} onClick={() => navigate(`/companies/${company.id}`)}><Avatar name={company.name} size={28}/><span><strong>{company.name}</strong><small>{company.regNo}</small></span><Badge tone={tone[company.verification]}>{company.verification}</Badge></button>)}</div></Card></aside>
    </div>
    <Modal open={addOpen} onClose={() => setAddOpen(false)} title="Add trucking company" description="Create a new company record." footer={<><Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button><Button onClick={saveCompany} disabled={!form.name || !form.regNo}>Add Company</Button></>}><div className="tc-form">{Object.entries({ name: "Company name", regNo: "RC number", contactName: "Contact person", contactPhone: "Phone", contactEmail: "Email", location: "Location" }).map(([key, label]) => <TextField key={key} label={label} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}/>)}</div></Modal>
  </div>;
}
